### ISSUE TITLE
going to rerender 3 times

### ISSUE THREAD

**Issue by alexey-ogarkov-db** [Mithc/react-blog-app#1]
https://github.com/Mithc/react-blog-app/blob/14c7a7af4494c9ec800d2a84046f3e9c805c9009/src/customHooks/useFetch.ts#L18

**Comment by Mithc** [comment]
Here I use React version 18, that has Automatic Batching feature, for previous versions it really should be several re-renders, and it could be fixed with unstable_batchedUpdates
